export const CREATE_USER = "CREATE_USER";
export const GET_USER = "GET_USER";
export const GET_USERS = "GET_USERS";
export const UPDATE_USER_PASSWORD = "UPDATE_USER_PASSWORD";
export const VALIDATION_USER_LOGIN = "VALIDATION_USER_LOGIN";
export const VALIDATION_USER_SIGNUP = "VALIDATION_USER_SIGNUP";